from routes.Admin_routes import *
from routes.Banned_member_routes import *
from routes.Customer_routes import *
from routes.Game_routes import *
from routes.Game_Report_routes import *
from routes.Notice_routes import *
from routes.Payment_routes import *
from routes.Rental_routes import *
from routes.Staff_routes import *